from PyQt4 import QtCore, QtGui
from add_window import Ui_addWindow
from update_window import Ui_updateWindow
import mysql.connector


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_accountWindow(object):
    def setupUi(self, accountWindow):
        accountWindow.setObjectName(_fromUtf8("accountWindow"))
        accountWindow.resize(1440, 700)
        accountWindow.setWindowIcon(QtGui.QIcon('logo.jpg'))
        self.centralwidget = QtGui.QWidget(accountWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 40, 1441, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Gothic"))
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1441, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Gothic"))
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 711, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Gothic"))
        font.setPointSize(22)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(720, 110, 711, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Gothic"))
        font.setPointSize(22)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 431, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Gothic"))
        font.setPointSize(22)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 240, 431, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Gothic"))
        font.setPointSize(22)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineNumber = QtGui.QLineEdit(self.centralwidget)
        self.lineNumber.setGeometry(QtCore.QRect(450, 169, 271, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Gothic"))
        font.setPointSize(22)
        self.lineNumber.setFont(font)
        self.lineNumber.setObjectName(_fromUtf8("lineNumber"))
        self.lineName = QtGui.QLabel(self.centralwidget)
        self.lineName.setGeometry(QtCore.QRect(450, 240, 271, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Gothic"))
        font.setPointSize(22)
        self.lineName.setFont(font)
        self.lineName.setText(_fromUtf8(""))
        self.lineName.setObjectName(_fromUtf8("lineName"))
        self.lineName.setFrameShape(QtGui.QFrame.Box)
        self.btnSearch = QtGui.QPushButton(self.centralwidget)
        self.btnSearch.setGeometry(QtCore.QRect(750, 170, 131, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Gothic"))
        font.setPointSize(12)
        self.btnSearch.setFont(font)
        self.btnSearch.setObjectName(_fromUtf8("btnAdd"))
        self.btnSearch.clicked.connect(self.searchDatabase)
        self.btnSearch.setStyleSheet("background-color: #1f70f2; color: white")
        self.btnUpdate = QtGui.QPushButton(self.centralwidget)
        self.btnUpdate.setGeometry(QtCore.QRect(1050, 240, 131, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Gothic"))
        font.setPointSize(12)
        self.btnUpdate.setFont(font)
        self.btnUpdate.setObjectName(_fromUtf8("btnUpdate"))
        self.btnUpdate.clicked.connect(self.goToUpdate)
        self.btnUpdate.setStyleSheet("background-color: #1f70f2; color: white")
        self.btnAdd = QtGui.QPushButton(self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(1050, 170, 131, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Gothic"))
        font.setPointSize(12)
        self.btnAdd.setFont(font)
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.btnAdd.clicked.connect(self.goToAdd)
        self.btnAdd.setStyleSheet("background-color: #1f70f2; color: white")
        self.tableWidget = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(190, 300, 901, 301))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Gothic"))
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.btnBack = QtGui.QPushButton(self.centralwidget)
        self.btnBack.setGeometry(QtCore.QRect(990, 620, 101, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Gothic"))
        font.setPointSize(12)
        self.btnBack.setFont(font)
        self.btnBack.setObjectName(_fromUtf8("btnBack"))
        accountWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(accountWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        accountWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(accountWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        accountWindow.setStatusBar(self.statusbar)

        self.retranslateUi(accountWindow)
        QtCore.QMetaObject.connectSlotsByName(accountWindow)

    def searchDatabase(self):
        meter = self.lineNumber.text()

        if str(meter) == "":
            warningBox = QtGui.QMessageBox()
            warningBox.setText("Please enter Meter Number.")
            warningBox.setIcon(QtGui.QMessageBox.Warning)
            warningBox.setWindowIcon(QtGui.QIcon('/home/martin/THESIS/Qt Design/logo.jpg'))
            warningBox.setWindowTitle("San Pascual Waterworks")
            warningBox.exec_()

        else:
            # conn = mysql.connector.connect(host="localhost",user="root",passwd="",db="sanpascualww")
            conn = mysql.connector.connect(host="localhost",user="root",passwd="Martinluther01",db="sanpascualww")
            mycursor = conn.cursor()

            mycursor2 = conn.cursor()

            mycursor2.execute("SELECT * from clients WHERE meterNumber = " + '"' + (str(meter)) + '"')
            data = mycursor.fetchall()

            for name in data:
                self.lineName.setText(str(name[1]))

            mycursor.execute('''SELECT * from client_records WHERE meterNumber LIKE %s LIMIT 100''', ("" + str(meter) + "%",))
            
            self.tableWidget.setRowCount(0)

            for row_number, row_data in enumerate(mycursor):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QtGui.QTableWidgetItem(str(data)))

            conn.commit()
            conn.close()

    def goToAdd(self):
        self.window = QtGui.QMainWindow()
        self.ui = Ui_addWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def goToUpdate(self):
        self.window = QtGui.QMainWindow()
        self.ui = Ui_updateWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def retranslateUi(self, accountWindow):
        accountWindow.setWindowTitle(_translate("accountWindow", "San Pascual Waterworks", None))
        self.label_2.setText(_translate("accountWindow", "Manage Accounts", None))
        self.label.setText(_translate("accountWindow", "San Pascual Waterworks", None))
        self.label_3.setText(_translate("accountWindow", "Search Accounts", None))
        self.label_4.setText(_translate("accountWindow", "Account Options", None))
        self.label_5.setText(_translate("accountWindow", "Meter Number", None))
        self.label_6.setText(_translate("accountWindow", "Name", None))
        self.btnUpdate.setText(_translate("accountWindow", "Update Account", None))
        self.btnAdd.setText(_translate("accountWindow", "Add Account", None))
        self.btnSearch.setText(_translate("accountWindow", "SEARCH", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("accountWindow", "Month", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("accountWindow", "Present Reading", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("accountWindow", "Prev. Reading", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("accountWindow", "Cubic Meter", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("accountWindow", "Amount", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("accountWindow", "Penalty", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("accountWindow", "Total Amount", None))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("accountWindow", "O.R. Number", None))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("accountWindow", "Date Issued", None))
        self.btnBack.setText(_translate("accountWindow", "BACK", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    accountWindow = QtGui.QMainWindow()
    ui = Ui_accountWindow()
    ui.setupUi(accountWindow)
    accountWindow.show()
    sys.exit(app.exec_())

